---
title: IDebugProcess2::CauseBreak | Microsoft-Dokumentation
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-sdk
ms.topic: conceptual
f1_keywords:
- IDebugProcess2::CauseBreak
helpviewer_keywords:
- IDebugProcess2::CauseBreak
ms.assetid: efda8865-2319-4d53-90bf-6d9d74cd5195
author: gregvanl
ms.author: gregvanl
manager: douge
ms.workload:
- vssdk
ms.openlocfilehash: 594e945a0805e9d14a358d98cfeb9a207e3da76f
ms.sourcegitcommit: 240c8b34e80952d00e90c52dcb1a077b9aff47f6
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/23/2018
ms.locfileid: "49856040"
---
# <a name="idebugprocess2causebreak"></a>IDebugProcess2::CauseBreak
Fordert an, dass es sich bei der n채chsten Ausf체hrung von Code in diesem Prozess, Programmieren Sie angehalten, und senden eine [IDebugBreakEvent2](../../../extensibility/debugger/reference/idebugbreakevent2.md) Ereignisobjekt.  
  
## <a name="syntax"></a>Syntax  
  
```cpp  
HRESULT CauseBreak(   
   void  
);  
```  
  
```csharp  
int CauseBreak();  
```  
  
## <a name="return-value"></a>R체ckgabewert  
 Wenn erfolgreich, wird `S_OK`ist, andernfalls ein Fehlercode zur체ckgegeben.  
  
## <a name="see-also"></a>Siehe auch  
 [IDebugProcess2](../../../extensibility/debugger/reference/idebugprocess2.md)