---
title: C26111
ms.date: 11/04/2016
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: a55e9420d230ffe1dc005330710074000ff82124
ms.sourcegitcommit: 42ea834b446ac65c679fa1043f853bea5f1c9c95
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 04/19/2018
---
# <a name="c26111"></a>C26111
Warnung C26111: wegen eines Fehlers beim Sperre Aufrufer \<Sperre > vor dem Aufruf von Funktion \<Func >.

 Die Anmerkung `_Requires_lock_not_held_` erzwingt eine Voraussetzung, dass die Anzahl der Sperren für die angegebene Sperren größer als 0 (null) sein kann, wenn die Funktion aufgerufen wird. C26111 Warnung wird ausgegeben, wenn eine Funktion ein Fehler auftritt, um die Sperre aufzuheben, bevor sie eine andere Funktion aufruft.

## <a name="example"></a>Beispiel
 Im folgende Beispiel wird die Warnung C26111 generiert, da die `_Requires_lock_not_held_` Vorbedingung verletzt wird, durch den Aufruf von `DoNotLock` innerhalb des Abschnitts gesperrt.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}

```