---
title: "C28125 | Microsoft Docs"
ms.custom: ""
ms.date: "12/02/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28125"
helpviewer_keywords: 
  - "C28125"
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 4
caps.handback.revision: 4
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C28125
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

warning C28125: The function must be called from within a try\/except block  
  
 Der Treiber ruft eine Funktion auf, die innerhalb eines „try\/except“\-Blocks aufgerufen werden muss, beispielsweise [ProbeForRead](http://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](http://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](http://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## Beispiel  
 Im folgenden Codebeispiel wird diese Warnung generiert:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 Im folgenden Codebeispiel wird diese Warnung vermieden:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```