---
title: C6312
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: caa2044c9bd36e8e7953bf2e7b1162f347bc8e04
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 01/02/2019
ms.locfileid: "53890218"
---
# <a name="c6312"></a>C6312
Warnung C6312: Mögliche Endlosschleife: Verwendung der EXCEPTION_CONTINUE_EXECUTION-Konstanten in der Ausnahmefilterausdruck einer try-mit Ausnahme

 Diese Warnung gibt an, die Verwendung der Konstante `EXCEPTION_CONTINUE_EXECUTION` (oder einer anderen Konstanten, die-1 ergibt) in einem strukturierten Ausnahmehandler Filterausdruck. Verwenden des konstanten Werts `EXCEPTION_CONTINUE_EXECUTION` kann zu einer Endlosschleife führen. Z. B. wenn eine Ausnahme von Hardware, die ausgelöst wurde, wird die Anweisung, die die Ausnahme verursacht hat neu gestartet werden. Wenn die Adresse, die die Ausnahme verursacht hat immer noch beschädigt ist, eine andere Ausnahme tritt auf, und Sie werden auf die gleiche Weise behandelt werden. Dies verursacht eine Endlosschleife.

 Ein expliziter Aufruf von `RaiseException` werden Ursache nicht direkt eine unendliche Schleife, es sind jedoch weiterhin Ausführung des Codes im protected-Block. Dies kann unerwartete sein und kann zu einer Endlosschleife führen, wenn `RaiseException` wurde verwendet, um zu vermeiden, einen ungültigen Zeiger zu dereferenzieren.

 In der Regel `EXCEPTION_CONTINUE_EXECUTION` nur von einer Funktion wird aufgerufen, in dem Filterausdruck, der hat die Möglichkeit, beheben Sie entweder den Zeiger, der die Ausnahme verursacht hat oder der zugrunde liegende Speicher zurückgegeben werden sollen.

## <a name="example"></a>Beispiel
 Der folgende Code generiert diese Warnung:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 So korrigieren Sie die Warnung unter Verwendung des folgenden Codes

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```