---
title: C6312 | Microsoft Docs
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: 766a3c670a41bb4f915c94c3f5d0df09fde11afe
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 04/16/2018
---
# <a name="c6312"></a>C6312
Warnung C6312: Mögliche Endlosschleife: Verwendung der EXCEPTION_CONTINUE_EXECUTION-Konstanten im Ausnahmefilterausdruck einer try-except-Anweisung.  
  
 Diese Warnung gibt an, die Verwendung der Konstanten `EXCEPTION_CONTINUE_EXECUTION` (oder eine andere Konstante, die-1 ergibt) in der Filter-Ausdruck von einem strukturierten Ausnahmehandler. Verwenden des konstanten Werts `EXCEPTION_CONTINUE_EXECUTION` zu einer Endlosschleife führen. Z. B. wenn eine Ausnahme von der Hardware ausgelöst wurde, wird die Anweisung, die die Ausnahme verursacht hat neu gestartet werden. Wenn die Adresse, die die Ausnahme verursacht hat immer noch beschädigt ist, wird eine andere Ausnahme erfolgt und auf die gleiche Weise behandelt werden. Dies verursacht eine Endlosschleife.  
  
 Ein expliziter Aufruf von `RaiseException` wird nicht direkt verursacht eine Endlosschleife, es wird jedoch weiterhin Ausführung des Codes in der geschützte Block. Dies kann unerwartete sein, und könnte zu einer Endlosschleife führen, wenn `RaiseException` wurde verwendet, um zu vermeiden, einen ungültigen Zeiger dereferenziert.  
  
 In der Regel `EXCEPTION_CONTINUE_EXECUTION` nur von einer Funktion aufgerufen wurden im Filterausdruck, besitzt eine Chance, zu beheben, die Zeiger, der die Ausnahme verursacht hat, oder der zugrunde liegende Arbeitsspeicher zurückgegeben werden soll.  
  
## <a name="example"></a>Beispiel  
 Der folgende Code generiert diese Warnung:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 So korrigieren Sie die Warnung unter Verwendung des folgenden Codes  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```